version: "3"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=GameStore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
